### ISSUE TITLE
пробно решение за anagram algorithm

### ISSUE THREAD

**Issue by Stefan-Markov** [luchob/softuni-spring-advanced-2021#1]
Здравейте, Лъчезар. Това е пробно решени за проблема - anagram algorith. Дали е приложимо ? https://github.com/StefanFMarkov/permutation/blob/main/Permutation.java - линк към решението. Прекарал съм го през Set<String> , защото като връща от call stack-а от рекурсията го пълни два пъти. Дано правилно давам issues/ pull request, че ми е за първи път и може въобще да не е както трябва.

**Comment by luchob** [comment]
Здравей! За упражнението - опитай да имплементираш метод, който да провери дали две думи са анаграми :-)

```
private static boolean areAnagrams(String word1, String word2) {
  // todo - add your implementation here
}
```

Ако се затрудниш виж 2-то issue тук - https://github.com/luchob/softuni-spring-advanced-2021/issues/2
То вече е затворено, но има коментар, който е релевантен.

Хмм... правилно си направил issue, но явно за pull request трябва да споменем 1-2 думи. Абе направо трябва да покажем как се прави, ако нямаш нищо против може да направя PR към твое репо по време на упражненията.

**Comment by Stefan-Markov** [comment]
Здравейте, аз съм разбрал, че трябва да изгенерирам всички варианти от "beer", а то е къде по-просто решението. Иначе може по време на лекцията да направите, ако има време  демо за git issue/ request.

**Comment by luchob** [comment]
Здрасти! :-) Може би аз не съм обяснил добре, но сега гледам в гит, че съм пушнал условието :-)

```
  public static void listAnagrams(List<String> words) {
    // TODO:
    // List all words that are anagrams.
    // Example: бира, риба, кавалер, акварел, пешо, софтуни
    // Expected output:
    // бира, риба
    // кавалер, акварел
}
```

Нищо де, от упражнения глава не боли! :-) Напротив.
