### ISSUE TITLE
Fetch API post method

### ISSUE THREAD

**Issue by StanislavI285** [luchob/softuni-spring-advanced-2021#10]
Здравей, Лъчо,

Надявам се, че всичко е наред и вече се възстановяваш от този досаден вирус.

Имам issue свързано с Fetch API и post метод. Целта ми е при натискане на бутон Send comment (article.html) чрез fetch api, да се добави коментар в базата, който след това да се върне като отговор и да се визуализира при останалите коментари,  но получавам отговор от сървъра със статус 403 - {timestamp: "2021-03-23T14:36:13.448+00:00", status: 403, error: "Forbidden", message: "Forbidden", path: "/comments/add"}.

[link](https://github.com/StanislavI285/SpringWebProject)

Поздрави,
Станислав

**Comment by luchob** [comment]
Хей, привет! 

Вирусът не е точно... "досаден"... той е... Франкенщайн. Някакъв миниатюрен урод с пипалца :-)

Това което веднага виждам тук, че липсва CSRF защита. Ако правиш POST и не пращаш CSRF токън към сървъра, грешката винаги ще е 403, точно както наблюдаваш. Ето какво имаш коментирано в секюрити конфигурацията:

```
        http.
//                csrf().disable(). //in html must be th:action instead of action, in order to have csrf token and the login to work properly
```

Това, което трябва да направиш е да изпечаташ токъна в HTML-a, напр:

```
<input
                                        type="hidden"
                                        th:name="${_csrf.parameterName}"
                                        th:value="${_csrf.token}" />
```
И да си го изпратиш и него на сървъра. Пробвай и пиши дали става. 

Надявам се, да съм бил полезен!

**Comment by StanislavI285** [comment]
Да, това беше проблемът. Много ти благодаря!
