### ISSUE TITLE
Проблем с тестовете

### ISSUE THREAD

**Issue by ivaka4** [luchob/softuni-spring-advanced-2021#11]
Здравей Лъчо,

Извинявам се че ти пиша и те занимавам докато си болен. 
Пиша ти отностно тестовете на сървисите, защото нещо не мога да разбера как стават нещата особено, като имам MultipartFiles нямам никаква представа какво става, ако може някаква помощ.

[GIT](https://github.com/ivaka4/watch-shop)

**Comment by luchob** [comment]
Ехе, няма проблем! Днес съм **много** развълнуван! За пръв път от **8 дни** насам имам нормална температура! Все едно съм се родил за 2-ри път... :-) И обонянието ми започва да се появява отново... Шшшшт... тихо да не чуе и да не го ядосаме, че няма абсолютно никакво чувство за хумор :-)

Относно файловете, първо може би ти е необходима in memroy DB за тестове, например H2.

```
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
```

Ако искаш интеграционни тестове с multipart file ползвай MockMultipartFile. За да не звучи голословно ето ти някакъв примерен тест, в контекста на проекта ти:

```
@SpringBootTest
@AutoConfigureMockMvc
@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
public class ProductControllerTest {

  @Autowired
  private MockMvc mockMvc;

  @Test
  @WithMockUser(username = "gosho", authorities = {"USER", "ADMIN"})
  void addProductTest() throws Exception {

    MockMultipartFile mockMultipartFile = new MockMultipartFile(
        "photos",
        "file.txt",
        MediaType.TEXT_PLAIN_VALUE,
        "This is the file content".getBytes());

    mockMvc.perform(MockMvcRequestBuilders
        .multipart("/product/add")
        .file(mockMultipartFile)
        .param("name", "TestName")
        .param("description", "Test description")
        .param("make", "Test make")
        .param("model", "Test model")
        .param("productNumber", "Test productNumber")
        .param("price", "10")
        .param("category", "books")
        .with(csrf()))
        .andExpect(status().is3xxRedirection())
        .andExpect(mvcResult -> {
          "/shop".equals(mvcResult.getModelAndView().getViewName());
        });
  }

}
```

**Comment by ivaka4** [comment]
Благодаря за примера, но искам да попитам например в сървиса как да тествам добавянето на продукт или нещо друго с добавяне или като тествам контролера така тествам и сървиса?

**Comment by ivaka4** [comment]
Ако може малка помощ, правя тестове за гет мапинга и ми хвърля това

![image](https://user-images.githubusercontent.com/69511821/112517154-ab1cb080-8da0-11eb-9900-9418c03ec88e.png)
![image](https://user-images.githubusercontent.com/69511821/112518890-832e4c80-8da2-11eb-9bef-1563532b0e88.png)

**Comment by luchob** [comment]
Привет - няколко коментара.

1. Да, като тестваш контролера, естествено тестваш и сървиса.
2. Все пак сървис лейъра може и често се тества с чисти JUnit/Mockito тестове
3. Има един много мощен механизъм за инджектване на мокове в апликейшън контекста - MockBean - вж. по-доле
4. Защо ти дава 404 не знам, при мен гърми по много по-различен начин...

Ето един много бърз скелет на примерен тест:

```
@SpringBootTest
@AutoConfigureMockMvc
@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
public class ProductControllerTest {

  private static final String TEST_USER = "gosho";

  @Autowired
  private MockMvc mockMvc;

  @MockBean
  UserService mockUserService;

  @WithMockUser(username = TEST_USER, authorities = "ADMIN")
  @Test
  void testHome() throws Exception {

    when(mockUserService.findByUsername(TEST_USER)).thenReturn(
        new UserServiceModel()//todo - maybe add some props here
    );

    mockMvc.perform(MockMvcRequestBuilders
        .get("/product/add"))
        .andExpect(status().is2xxSuccessful());
  }

}
```
