### ISSUE TITLE
Проблем с логина

### ISSUE THREAD

**Issue by Iliyan02** [luchob/softuni-spring-advanced-2021#12]
Здравейте, имам проблем с логина не знам защо не работи прегледах и сравнявах security частта доста пъти, но не можах да го оправя.               https://github.com/Iliyan02/ProjectDemo-Defense

**Comment by luchob** [comment]
Здравей! В линка, който си ми дал не виждам никаква секюрити конфигурация? Грешен линк ли си ми дал?

**Comment by Iliyan02** [comment]
Не се беше комитнало както трябва.
https://github.com/Iliyan02/ProjectDemo
Ето

**Comment by luchob** [comment]
Здрасти!

Извинявай, че се мотаех толкоз с отговора, ама... малкият кашличко е виновен :-) Наред ти е конфикурацията, обаче виждам, че имаш това нещо в head-a си:

```
<link rel="stylesheet" href="min.js">
```

Не съществува такъв скрипт и той се обърква и те пренасочва на грешно място... Просто го изтрий и пробвай пак.

Поздрави,
Л.

**Comment by Iliyan02** [comment]
Няма проблем, стана! Благодаря много! Бързо оздравяване!
