### ISSUE TITLE
DB issue

### ISSUE THREAD

**Issue by dena8** [luchob/softuni-spring-advanced-2021#13]
Здравей, Лъчо
Надявам се, че вече си спечелил битката с COVID! ;)
Открих нещо, което ме озадачи - записа на името на юзъра в базата е case-insensitive и мога да достъпя съответния юзър 
по различен начин. Например в базата ми е записан username - Zajo, a ако потърся ZaJo или zAjO пак ми връща този юзър. Това не ми се вижда никак редно! 
Може ли да кажеш защо се получава така и как мога да оправя това?
Прилагам скрииншот: 
![Zajо](https://user-images.githubusercontent.com/46784147/112554157-74f62580-8dce-11eb-8e3f-c72a50cb0057.png)
Благодаря за вниманието!

**Comment by luchob** [comment]
Привет! Чак спечелил - не, но вече имам някакви малки постижения. Това, което наблюдаваш се нарича [колация](https://www.mysqltutorial.org/mysql-collation/). Ето примерче:

```
CREATE TABLE `test` (
  `name` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL
)

insert into test values ('PeShO')

select count(*) from test where name = 'PESHO'
-> 1

drop table test


CREATE TABLE `test` (
  `name` varchar(20) COLLATE utf8_bin NOT NULL
)

insert into test values ('PeShO')

select count(*) from test where name = 'PESHO'
-> 0
```

В линка пише как може да сменяш колацията на цялата ДБ.

Поздрави!
