### ISSUE TITLE
Тестове

### ISSUE THREAD

**Issue by angelnangelov** [luchob/softuni-spring-advanced-2021#14]
Здраей, Лъчо,
 пожелавам ти бързо да се оправяш от този коварен вирус. Ако имаш възможност, може ли да ми помогнеш?
Имам проблем с тестовете. Нещо не мога да разбера, как точно се работи с това мокито. Сложил съм едно TODO: question в тестовете, можеш ли да го погледнеш и да ми кажеш къде бъркам? Също така не ми показва Code Coverage, нещо не мога да го настроя.
Поздрави,
Ангел
git: https://github.com/angelnangelov/remontbg

**Comment by luchob** [comment]
Привет! Ами идеята на това мокито е когато имаш един клас с няколко депендънсита, например:

```
public class ToTest {
   private DepA depA;
   private DepB depB;

   public int doWork(int a, int b) {
      return depA.calc(a) + depB.calc(b);
   }
}

```
Да имаш механизъм с който да замениш депендънситата с "мокове", кухи класове, което да ти позвои да тестваш самия клас (ToTest) без да се интересуваш как работят самите депендънсита. Да речем че имаш UserServiceImpl в които имаш UserRepository. Нека да заменим UserRepository-то с mock, така че да се уверим, че мапинга между ентити и модел се създава нормално и правилно. Ето приблизително как би изглежда теста:
```
@RunWith(MockitoJUnitRunner.class)
public class UserServiceTests {

    @Mock
    UserRepository mockUserRepository;
    @Mock
    RoleService mockRoleService;
    @Mock
    BCryptPasswordEncoder mockEncoder;
    @Mock
    EmailService mockEmailService;

    UserServiceImpl serviceToTest;

    @Before
    public void initTests() {
        serviceToTest = new UserServiceImpl(
            new ModelMapper(),
            mockUserRepository,
            mockRoleService,
            mockEmailService,
            mockEncoder
        );

    }

    @Test
    public void findUserByUsername_WhenUserExist_ShouldWork() {

        // setup a test user
        User testUser = new User();
        testUser.setUsername("pesho");
        testUser.setEmail("pesho@example.com");
        //todo: more props here...
        Role sampleRole = new Role();
        sampleRole.setAuthority("TEST_AUTHORITY");
        testUser.setAuthorities(Set.of(sampleRole));

        // configure the mock user repo
        Mockito.when(mockUserRepository.findUserByUsername("pesho"))
            .thenReturn(Optional.of(testUser));

        // test
        UserServiceModel result = serviceToTest.findUserByUsername("pesho");

        //verify
        Assert.assertEquals(result.getUsername(), testUser.getUsername());
        Assert.assertEquals(result.getEmail(), testUser.getEmail());
        Assert.assertEquals(1, result.getAuthorities().size());
        //todo compare if the role is correct
    }
}
```

**Comment by angelnangelov** [comment]
Благодаря !

**Comment by luchob** [comment]
<img width="606" alt="Screenshot 2021-03-26 at 9 47 06" src="https://user-images.githubusercontent.com/10339738/112599214-50bf3680-8e18-11eb-8a1f-f23c3b531903.png">

**Comment by angelnangelov** [comment]
Да , но ми излиза No  coverage results. Click Edit to fix configuartiuon settings

**Comment by luchob** [comment]
Да, защото пускаш текущ клас и настройките са малко... замазани. Може да ги оправиш, напр:

<img width="1058" alt="Screenshot 2021-03-26 at 13 20 09" src="https://user-images.githubusercontent.com/10339738/112624219-0187fe80-8e36-11eb-9596-417c3f5900f8.png">
<img width="671" alt="Screenshot 2021-03-26 at 13 20 29" src="https://user-images.githubusercontent.com/10339738/112624260-0d73c080-8e36-11eb-8fe5-ee34d0d99569.png">

Или да пуснеш на руут папката run with coverage:
<img width="334" alt="Screenshot 2021-03-26 at 13 21 17" src="https://user-images.githubusercontent.com/10339738/112624340-31370680-8e36-11eb-8e80-9cd2cf33d789.png">

**Comment by angelnangelov** [comment]
Благодаря отново !

**Comment by angelnangelov** [comment]
Здравей отново, след вчерашната лекция всичко стана доста по-ясно, даже успях да напиша няколко теста, но имам проблем при тестването на контролерите ,когато ползвам Principal в самия контролер. Ако е възможно можеш ли да погледнеш? Маркирал съм теста с    "    //TODO : QUESTION: не успява да ми намери юзъра(Principal), който ползвам в контролера".
 Благодаря предварително.
git: https://github.com/angelnangelov/remontbg

**Comment by luchob** [comment]
Здравей!

Имам странен проблем с проекта ти :-) Трябва да избереш да ползваш или properties или yaml за application file-a. Освен това в твоите тестови ресурси е на грешно място, трябва да е така:

<img width="297" alt="Screenshot 2021-03-27 at 18 33 38" src="https://user-images.githubusercontent.com/10339738/112727387-fa8ee800-8f2a-11eb-878d-2ce8a7c91fb6.png">

Забележи, че е на едно ниво с Java. Като отстраних тези неща ми принципала ми се резолва:

<img width="1028" alt="Screenshot 2021-03-27 at 18 35 18" src="https://user-images.githubusercontent.com/10339738/112727447-332ec180-8f2b-11eb-9b5e-614a19732ad0.png">

А за да се справиш с cloudinary service може в самия интеграционен тест да инджектваш мокове в апликейшън контекста. Виж как става с анотацията @MockBean

Поздрави, 
Л.

**Comment by angelnangelov** [comment]
Благодаря, бях забравил да  commitna yaml ,който е за проекта. Аз успях да се справя като мокнах и принципала , но сега ще го оправя.
![problem](https://user-images.githubusercontent.com/63353718/112727681-53ab4b80-8f2c-11eb-856d-7622d45a775b.PNG)
