### ISSUE TITLE
Search bar problem

### ISSUE THREAD

**Issue by Iliyan02** [luchob/softuni-spring-advanced-2021#15]
Здравей, Лъчо! Имам проблем със search bar-а. Може ли да погледнеш?
https://github.com/Iliyan02/Project

**Comment by luchob** [comment]
Здравей! Може ли да ми опишеш проблема в малко повечко детайли, но преди това да погледнеш това нещо дали ще ти помогне? -> https://github.com/luchob/softuni-music-db/issues/16

**Comment by Iliyan02** [comment]
Като цяло проблемът ми е в това, че когато търся някой филм, той не се визуализира, а аз искам да е като при проекта от workshop-a. Пробвах да връщам MovieViewModel както ти каза, но ми дава грешка. 
 https://imgur.com/KJGl86A

**Comment by luchob** [comment]
Разбира се, че дава грешка и самата грешка е много добре говоряща. :-)

То очаква `ResponseEntity<List<MovieViewModel>>` а ти му даваш `ResponseEntity<List<MovieEntity>>`

Трябва да мапнеш ентититата в вю модели. Ето ти пример:

```
@GetMapping("/api")
   public ResponseEntity<List<MovieViewModel>> findAll(){
       return ResponseEntity
               .ok()
               .body(movieRepository.
                   findAll().
                   stream().
                   map(e -> modelMapper.map(e, MovieViewModel.class)).
                   collect(Collectors.toList()));
   }
```

**Comment by Iliyan02** [comment]
Благодаря! Но проблема е, че script-a за search-bar-a не намира масива от филми след като се логна. https://imgur.com/JktQ7vt. Но когато го търся по URL ги намира: https://imgur.com/CkdTR8Q и след това пак не се визуализират когато търся филм.

**Comment by luchob** [comment]
Привет, значи трябва да отделиш внимание на грешките в Javascript-овете ти :-) Нека видим home.html:

```
<script th:replace="fragments/fragment :: script"></script>
```

Какво има в този скрипт и как работи?

```
<script th:fragment="script">
   
    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // When the user clicks on the button, open the modal
    btn.onclick = function() {
        modal.style.display = "block";
    }
</script>
```

Грешката е `Cannot set property 'onclick' of null`, което е ОК защото няма бутон myBtn. 
Да работи сърч бара пък изобщо не може и да става въпрос, защото ти не го инклудваш в home страницата и той не се зарежда.
