### ISSUE TITLE
Api Problem

### ISSUE THREAD

**Issue by Iliyan02** [luchob/softuni-spring-advanced-2021#16]
Здравей, Лъчо :)! Защо при логване се визуализира масива от филми от javascript кода, а не ме редиректва към /home.
Сигурно е някаква малка грешка, но се показа от както search бара започна да работи.
https://github.com/Iliyan02/ProD
https://imgur.com/AawlqUV

**Comment by luchob** [comment]
Привет! Няма никаква причина да включваш javascript-овете като фрагменти. Причината е, че не се парсват коректно. Изкарай ги в статичен ресурс - resources/static/js и ги импортвай като истински JS и така ще се оправят нещата. При интерес за повече детайли - https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#javascript-inlining
