### ISSUE TITLE
Проблем с @PreAuthorize("hasRole('ADMIN')")

### ISSUE THREAD

**Issue by tek0t0** [luchob/softuni-spring-advanced-2021#18]
Здравей Лъчо, 
Не знам дали още отговаряш на въпроси, относно курса и проекта, но все пак реших да ти пиша, защото с дни вече си чупя главата и не мога да разбера какъв е проблема. Много ще се радвам, ако хвърлиш едно око. 
Става въпрос за следното: опитах се да огранича достъпа до определени методи в UserControllera с @PreAuthorize("hasRole('ADMIN')") анотацията, но при опит за регистриране на нов юзър, приложението гръмва с "Cannot invoke "bg.softuni.needadrink.service.UserService.emailExists(String)" because "this.userService" is null".
Това се случва само в UserControllera,  на който и метод да сложа тази анотация. Пробвах и с @Secured("ROLE_ADMIN"), същото положение. Мога да се логна със съществуващ юзър и рестрикциите работят, но при опит за регистрация гръмва. 
Ето линк към проекта ми:  https://github.com/tek0t0/need-a-drink

Благодаря предварително и поздрави.

**Comment by luchob** [comment]
Здравей! 

Опитвам се да отговарям, просто ми е необходимо малко повечко време. Тъпо е да не отговарям след толкоз приказки заедно :-)

Може ли да се увериш, че всички методи на `UserController` са публични? Ако не са, то AOP-a не може да се извърши успешен autowire.  Ако това не реши проблема, пиши тук :-)

Поздрави,
Л.

**Comment by tek0t0** [comment]
Това е бил проблема... единия метод беше прайвит и въобще не съм го видял... Жив и здрав да си :) Блъскам си главата в бюрото в момента... Благодаря ти много!!!

Поздрави,
Стоян

**Comment by luchob** [comment]
Радвам се, че помогнах! Успех на изпита!

Л.
