### ISSUE TITLE
proect

### ISSUE THREAD

**Issue by chaneto** [luchob/softuni-spring-advanced-2021#19]
Здравей, Лъчо. Относно проекта, би ли било полезно или по скоро задължително при стартирането му да се генерират няколко категории примерно за улеснение на проверяващите и продукти примерно ако проекта е такъв разбира се, и ако трябва нужно ли е да са много или няколко просто за да се разгледа проекта трябват.

**Comment by luchob** [comment]
Привет! 

Да, бих казал, че идеята е добра и дори почти задължителна за да си представиш проекта в добра светлина. Можеш да направиш някаква заготовка като ползваш, например:

- CommandLineRunner;
- data.sql
- liquibase
- нещо друго

Много ми се иска да ви покажа liquibase защото е готин проект и се интегрира добре със Спринг. Освен това, би трябвало да вземе точица или две като "нещо друго полезно", както се казваше в заданието. Дано времето ни стига, че тази част от курса си е едно препускане нон-стоп. Щеше да е идеално ако бяха предвидили още 2 занятия.

За изпита не се притеснявай, но го приеми като възможност да порепетираш за "голямата сцена" по натам :-)

Поздрави,
Л.
