### ISSUE TITLE
Решение на anagrams

### ISSUE THREAD

**Issue by DoytchoConkov** [luchob/softuni-spring-advanced-2021#2]
Ето , какво сътворих: https://github.com/DoytchoConkov/InterviewsTests
P.S. нещо не ми се получи pull request-a . Ако е удобно може ли да покажете как става в следващата лекция. Много е добре , че ни давате такива задачки , хем се упражняваме , хем и ще имаме повече самочувствие , като ходим на интервюта.

**Comment by luchob** [comment]
Здравей! Супер е, че се упражняваш и има интерес. Алгоритъмът ти за намиране на анаграма на две думи изглежда **почти** правилен (но честно не съм го пускал). Но от друга страна има и по-четливи решения. Например ако "сортираш" два **различни** стринга и те вече са еднакви, то те са анаграми:

```
 private static boolean areAnagrams(String word1, String word2) {
    if (word1.length() != word2.length() || word1.equalsIgnoreCase(word2)) {
      return false;
    }

    return sortString(word1).equalsIgnoreCase(sortString(word2));
  }

  private static String sortString(String s) {
    char[] chars = s.toCharArray();
    Arrays.sort(chars);
    return new String(chars);
  }
```

Защо казвам "почти правилен". Защото:

1. Еднаквите думи не са анаграми - напр. бира и бира.
2. Думите с различни главни букви са анаграми - напр. Риба и Бира.

Ще направим едно решение на лекцията пред всички, мисля че има интерес!

Поздрави,
Л.
