### ISSUE TITLE
Проблем Spring Security

### ISSUE THREAD

**Issue by angelnangelov** [luchob/softuni-spring-advanced-2021#3]
Имам проблем, след като регистрирам потребител и го запазя в базата , не успявам да го логна. Не мога да открия какво бъркам.
link: https://github.com/angelnangelov/remont-project
Поздрави,
Ангел

**Comment by luchob** [comment]
Здравей! Много весел дизайн :-) Макар че, виждам някакви проблемчета с JS, например. И разни други нещица, но трябва още работа.

Относно проблема ти - голямото бъркане е, че си пропуснал да имплементираш и регистрираш твой собствен `UserDetailsService`. Това е класът, който Spring използва за да му подаде userName и да получи една Spring специфична репрезентация на потребителя. В едно с passwordEncoder-a Spring може да направи аутентикация. Без тези класове не може да се логнеш.

Направих ти примерен pull request в репозиторито, който може да разгледаш. Тъй като редиректа към home не работи добре :-) като се логнеш отиди директно на localhost:8080/home и ще видиш юзър името си. 

Надявам се да са полезни инструкциите.

Поздрави,
Л.

**Comment by angelnangelov** [comment]
Благодаря!

**Comment by angelnangelov** [comment]
Здравей, Лъчо ! Имам още един проблем със Security, когато ползвам      @PreAuthorize("isAuthenticated()") в OfferController и ToolController ми сетва всички полета:
  private final UserService userService;
    private final ModelMapper modelMapper;
    private  final OfferService offerService;
    private final ToolOfferService toolOfferService;
    private final CommentService commentService;
на null, ако имаш свободно време да разгледаш и другите неща много ще се радвам да ми дадеш някакви препоръки :)
repo : https://github.com/angelnangelov/remontbg 
Поздрави, 
Ангел

**Comment by luchob** [comment]
Здрасти! 

Малко бързам, но ето няколко съвета, дано помогнат. Ако не, пиши ми пак тук.

За контролера: @PreAuthorize няма да работи върху private методи. Направи методите в контролера public. :-) Меджииик :-)  Второ, не мисля че ти е необходимо PreAuthorize въобще след като вече си дефинирал кои ендпойнти са достъпни в security configuration-a. Имаш ли някаква конкретна идея? 

И последно - моля те... махни си паролите от application.propeties :D и ги смени... Това е много важно :-)

Засега толкоз - чакам да ми драснеш ред!

Поздрави,
Л.

**Comment by angelnangelov** [comment]
Да , така всичко се оправи , а за application.propeties знам просто този емайл го направих специално за проекта затова съм ги оставил. Благодаря отново.
Лека вечер,
Ангел

**Comment by angelnangelov** [comment]
Здраей, Лъчо,
пак съм аз... Пожелавам ти бързо да се оправяш от този коварен вирус. Ако имаш възможност, може ли да ми помогнеш?
Имам проблем с тестовете. Нещо не мога да разбера, как точно се работи с това мокито. Сложил съм едно TODO: question  в тестовете, можеш ли да го погледнеш и да ми кажеш къде бъркам?
Поздрави,
Ангел
git: https://github.com/angelnangelov/remontbg

**Comment by luchob** [comment]
Привет! Ами идеята на това мокито е когато имаш един клас с няколко депендънсита, например:

```
public class ToTest {
   private DepA depA;
   private DepB depB;

   public int doWork(int a, int b) {
      return depA.calc(a) + depB.calc(b);
   }
}

```
Да имаш механизъм с който да замениш депендънситата с "мокове", кухи класове, което да ти позвои да тестваш самия клас (ToTest) без да се интересуваш как работят самите депендънсита. Да речем че имаш UserServiceImpl в които имаш UserRepository. Нека да заменим UserRepository-то с mock, така че да се уверим, че мапинга между ентити и модел се създава нормално и правилно. Ето приблизително как би изглежда теста:
```
@RunWith(MockitoJUnitRunner.class)
public class UserServiceTests {

    @Mock
    UserRepository mockUserRepository;
    @Mock
    RoleService mockRoleService;
    @Mock
    BCryptPasswordEncoder mockEncoder;
    @Mock
    EmailService mockEmailService;

    UserServiceImpl serviceToTest;

    @Before
    public void initTests() {
        serviceToTest = new UserServiceImpl(
            new ModelMapper(),
            mockUserRepository,
            mockRoleService,
            mockEmailService,
            mockEncoder
        );

    }

    @Test
    public void findUserByUsername_WhenUserExist_ShouldWork() {

        // setup a test user
        User testUser = new User();
        testUser.setUsername("pesho");
        testUser.setEmail("pesho@example.com");
        //todo: more props here...
        Role sampleRole = new Role();
        sampleRole.setAuthority("TEST_AUTHORITY");
        testUser.setAuthorities(Set.of(sampleRole));

        // configure the mock user repo
        Mockito.when(mockUserRepository.findUserByUsername("pesho"))
            .thenReturn(Optional.of(testUser));

        // test
        UserServiceModel result = serviceToTest.findUserByUsername("pesho");

        //verify
        Assert.assertEquals(result.getUsername(), testUser.getUsername());
        Assert.assertEquals(result.getEmail(), testUser.getEmail());
        Assert.assertEquals(1, result.getAuthorities().size());
        //todo compare if the role is correct
    }
}
```
