### ISSUE TITLE
Problem with cloudinary

### ISSUE THREAD

**Issue by ElenaTasheva** [luchob/softuni-spring-advanced-2021#5]
Здрасти Лъчо,
това е репозиторито за личния ми проект - 
https://github.com/ElenaTasheva/journal 
При стартирането на проекта Bean-a не се инициализира и гърми с грешка 
Could not resolve placeholder 'cloudinary.cloud-name' in value "${cloudinary.cloud-name}
В application.yml  също пропъртитата са подчертани и излиза съобщение 
"Cannot resolve configuration property 'spring.cloudinary.cloud-name'

Благодаря за съдействието!
Поздрави, 
Елена

**Comment by luchob** [comment]
Здравей, Ели!

Грешката е тривиална. Тъй като в `yaml` файла си подравнила cloudinary да е с таб (или нов ред) навътре, той си мисли, че пропъртито ти всъщност е `spring.cloudinary.cloud-name`, а не `cloudinary.cloud-name`. Подравни го да започва от началото на реда, именно така:

<img width="303" alt="Screenshot 2021-03-12 at 11 27 14" src="https://user-images.githubusercontent.com/10339738/110920370-f6a57800-8325-11eb-995d-55c40451a697.png">

Ако имаш още проблеми, отваряй issue-s смело, ще помагам. :-)

Поздрави,
Л.
