### ISSUE TITLE
Въпрос относно проект

### ISSUE THREAD

**Issue by ivaka4** [luchob/softuni-spring-advanced-2021#6]
Здравей, може ли да хвърлиш едно око на проекта ми. Да кажеш мнание и според теб правилно ли вървят нещата. За сега имам регистър логин, профил пейжд, ъплоад продукти, смяна на роли и добавяне на роли. Ако може да кажеш дали съм направ път, [Линк към гит](https://github.com/ivaka4/watch-shop). Като цяло имам още неща за правене. Трябва да направя добавяне на блогове и cloudinary също мисля да имплементирам и mail service също.

**Comment by luchob** [comment]
Здравей! 

Попрегледах кода и мисля, че определено си на прав път. Няколко неща ми направиха впечатление в security config-a:

Това **определено** не ми харесва :-)

```
.cors().disable()
.csrf().disable()
```

Ако пък използваш това: `.failureUrl("/users/login") ще имаш малко проблемче, което описахме в началото на предната лекция, ако искаш изслушай първото видео. Нищо особено. Понякога връщаш от контролера сървис модел вместо вю модел, което противоречи на пуритантството, изповядвано в СофтУни :-) Например в `ProductController`:
```
modelAndView.addObject("categories", productCategoryService.findAll());
```
Значи view model-a отива в темплийтите, binding model-a идва в контролера "от браузъра" service model-a е вход/изход в сървис лейъра. Честно казано, в реални проекти чак толкоз чистичко не съм го виждал никога, обикновено има едно dto и толкоз :-)

Но като цяло кода ти е добре структуриран и си на прав път. Давай смело и уверено напред и ми напомни да го погледна след няколко дни отново!

Поздрави,
Л.
