### ISSUE TITLE
Principal - setUser 

### ISSUE THREAD

**Issue by ElenaTasheva** [luchob/softuni-spring-advanced-2021#7]
Здрасти Лъчо, 
ще може ли да покажеш на лекцията във вторник как е най-правилният вариант да set-ваме user-a, когато имаме релация между таблиците и трябва да използваме currentLogged in user.
Към момента аз ползвам този метод, но ми се струва, че трябва да има по-умен вариант, така че да не го повтарям навсякъде, защото всеки път също така правя заявка към базата данни, за да го извлека. 

public String getCurrentUserEmail () {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        UserDetails userDetails = (UserDetails) authentication.getPrincipal();
        return userDetails.getUsername();
    }

Линк към репозиторито: https://github.com/ElenaTasheva/journal/
Благодаря!

**Comment by luchob** [comment]
Здравей, Ели!

Има един капан, който се нарича "premature optimization" :-) Разтърси се в гугъл за него. Колко често наистина ти се налага да теглиш текущия юзър от ДБ и защо? Бих заложил, например на създаването на някакъв обект, който има релация към текущия юзър, например в журнала, това е Comment. Но ти не създаваш по коментар на всеки рекуест. Дори и да го правиш, това отново не е проблем, тъй като колонката `email` е уникална:

```
    @Column(unique = true,nullable = false)
    public String getEmail() {
        return email;
    }
```

Това предполага уникален индекс върху нея, както би могла да видиш от DDL-а на таблицата:

```
CREATE TABLE `users` (
  ...
  `email` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  ...
  UNIQUE KEY `UK_6dotkott2kjsp8vw4d0m25fb7` (`email`)
)
```
Select по уникален индекс е много бърза операция, а аз наистина се съмнявам, че ти се налага да я правиш често. Стандартният начин да се сдобиеш с текущия юзър е през контролера:
```
 @GetMapping("/mapping")
  public ModelAndView admin(@AuthenticationPrincipal UserDetails user) {
     service.doSomething(user);
  }
```

Това, което виждам в `IncomeServiceImpl`:
```
@Service
public class IncomeServiceImpl implements IncomeService {

    private User user;
}
```
не е ОК, защото сървиса е singleton и всички логнати юзъри използват един и същ инстанс на този сървис. Може ли тук да ми кажеш един конкретен use-case за който ти е необходим текущия юзър? 

Освен това, искам да добавя, че освен `UserDetails` ти можеш да слагаш като принципал и твоя собствна имплементация на UserDetails в която да има каквото пожелаеш. Тази имплементация е достъна през `@AuthenticatedPrincipal`.

Чакам по-конкретен пример...

Поздрави,
Л.

**Comment by ElenaTasheva** [comment]
Здравей Лъчо и благодаря за помощта.
Аз сега виждам, че съм изпуснала да добавя в Income and Expense entity - User ентити. Бих искала те да имат релация с User, така както Daily Task, , за да мога да давам/показвам информация само за Currently Logged in user. Нещо взех да се обърквам дали това е правилен начин да свържа ентититата. Благодаря за решението да взимам User-a през контролера, но аз пак реално ще трябва да направя заявка към базата, за да го сетна при създаването на нов Expense, Income или Task?

**Comment by luchob** [comment]
Привет отново!

Да, това че ще вземаш юзъра (при това по индекс) от ДБ при създаване на няколко вида ентитита не би трябвало да е никакъв проблем.

Правилно конфикуриран сървър може да пуска дори милион такива куерита за 1 секунда:

![MySQL 8](https://www.mysql.com/common/images/benchmarks/mysql_80_benchmarks_readonly.png)

Ако си спомняш, в mobilele имахме [такъв обект](https://github.com/luchob/softuni-cars/blob/main/src/main/java/bg/softuni/cars/models/entities/OfferEntity.java#L106). И в сървиса [по подобен начин](https://github.com/luchob/softuni-cars/blob/main/src/main/java/bg/softuni/cars/services/impl/OfferServiceImpl.java#L56) правихме нещата.

Естествено, там не ползвахме спринг секюрити и всичко беше една кръпчица, но в случая можеш да си вземаш юзъра през контролера.  От друга страна, бих те посъветвал да изтриеш релациите от страната на юзъра (от java кода на ентитито), защото реално в твоя (а не само в твоя) проект, юзъра би имал огромно количество релации и зареждането му (особено ако е са eager fetch) ще бъде неприятно.

Така task entity ще има релация към юзъра, а user entity ще е изчистено. После може съвсем лесно да вземеш всички таскове на юзъра с една заявка, като напишеш findAllBy.... метод в `TaskRepository`.

Поздрави,
Л.
