### ISSUE TITLE
Проблем с клауда

### ISSUE THREAD

**Issue by ivaka4** [luchob/softuni-spring-advanced-2021#8]
Здравей, имам проблем когато добавих клауда и сложих в биндинг модела MultipartFile ми хвърля грешка още в биндига и не може да стигне до сървиса, опитах няколко неща, но нищо не се оправя. Ето я грешката в bindingResult-а. 
Линк към гит [Watch-Shop](https://github.com/ivaka4/watch-shop)
`org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'productAddBindingModel' on field 'photos': rejected value [20200408_213720.jpg,61269429_2707818015913375_6200489254095683584_o.jpg,116619451_1433775260165438_6314448291511257474_n.jpg]; codes [typeMismatch.productAddBindingModel.photos,typeMismatch.photos,typeMismatch.[Lorg.springframework.web.multipart.MultipartFile;,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [productAddBindingModel.photos,photos]; arguments []; default message [photos]]; default message [Failed to convert property value of type 'java.lang.String[]' to required type 'org.springframework.web.multipart.MultipartFile[]' for property 'photos'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.springframework.web.multipart.MultipartFile' for property 'photos[0]': no matching editors or conversion strategy found]`

**Comment by luchob** [comment]
Здравей!

Един бърз поглед ме навежда на мисълта, че си дефинирал формата непълно. Трябва да имаш enctype, например:
```
    <form ... th:method="post" enctype="multipart/form-data">
```
Това ли е причината? Ако имаш проблеми с клауда, хвърли едно око на [демото](https://github.com/luchob/softuni-spring-advanced-2021/tree/master/cloudinary), което правихме.

Поздрави,
Л.

**Comment by ivaka4** [comment]
Да точно го оправих, видях че м липсва това във формата вече работи
